name: Flutter CI

on: [push]

jobs:
  build:
    name: Build APK and App Bundle
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'latest' # or specify the version you are using, e.g., '3.7.0'

    - name: Flutter pub get
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Build App Bundle
      run: flutter build appbundle --release

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Upload App Bundle
      uses: actions/upload-artifact@v2
      with:
        name: app-release.aab
        path: build/app/outputs/bundle/release/app-release.aab
